name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up dependencies
        run: |
          cd ${GITHUB_WORKSPACE}/..
          git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-common.git
          cd vlingo-common && mvn install -DskipTests=true
          cd ${GITHUB_WORKSPACE}/..
          git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-actors.git
          cd vlingo-actors && mvn install -DskipTests=true
          cd ${GITHUB_WORKSPACE}/..
          git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-lattice.git
          cd vlingo-lattice && mvn install -DskipTests=true
          cd ${GITHUB_WORKSPACE}/..
          git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-schemata.git
          cd vlingo-schemata && mvn install -DskipTests=true
          cd ${GITHUB_WORKSPACE}/..
          git clone --depth=50 --branch=master https://github.com/vlingo/vlingo-build-plugins.git
          cd vlingo-build-plugins && mvn install -DskipTests=true
          cd ${GITHUB_WORKSPACE}

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install

      - name: Notify slack
        if: always() && github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: vlingo-ci
          SLACK_USERNAME: Bob the Builder
          SLACK_ICON: 'https://vlingo.io/wp-content/uploads/cropped-vlingo-favicon-180x180.png'
          SLACK_FOOTER: '${{ github.repository }}'

      - name: Cleanup
        run: rm -rf ~/.m2/repository/io/vlingo
